import { sql, defineRelationsPart } from 'drizzle-orm'
import {
    index,
    integer,
    primaryKey,
    real,
    sqliteTable,
    text,
    uniqueIndex,
} from 'drizzle-orm/sqlite-core'

// Generated by Site Admin. Edit site-admin.config.ts, then regenerate.

export const entries = sqliteTable(
    'site_admin_entries',
    {
        id: text().primaryKey(),
        model: text().notNull(),
        locale: text().notNull().default(''),
        translation_group: text().notNull(),
        current_revision_id: text(),
        published_revision_id: text(),
        scheduled_revision_id: text(),
        scheduled_at: text(),
        sort_order: real(),
        version: integer().notNull().default(0),
        created_at: text().notNull(),
        updated_at: text().notNull(),
        published_at: text(),
    },
    (table) => [
        uniqueIndex('site_admin_entries_translation').on(
            table.model,
            table.translation_group,
            table.locale,
        ),
        index('site_admin_entries_model').on(table.model),
        index('site_admin_entries_schedule')
            .on(table.scheduled_at)
            .where(sql`${table.scheduled_revision_id} IS NOT NULL`),
    ],
)

export const revisions = sqliteTable(
    'site_admin_revisions',
    {
        id: text().primaryKey(),
        entry_id: text()
            .notNull()
            .references(() => entries.id, { onDelete: 'cascade' }),
        slug: text().notNull(),
        actor_id: text(),
        created_at: text().notNull(),
    },
    (table) => [index('site_admin_revisions_entry').on(table.entry_id, table.created_at)],
)

export const assets = sqliteTable(
    'site_admin_assets',
    {
        id: text().primaryKey(),
        storage: text().notNull(),
        key: text().notNull(),
        content_type: text().notNull(),
        size: integer().notNull(),
        checksum: text(),
        metadata: text().notNull().default('{}'),
        state: text().notNull(),
        operation_token: text(),
        lease_expires_at: text(),
        created_at: text().notNull(),
        updated_at: text().notNull(),
    },
    (table) => [
        uniqueIndex('site_admin_assets_key').on(table.storage, table.key),
        index('site_admin_assets_gc').on(table.state, table.created_at),
    ],
)

export const relations = sqliteTable(
    'site_admin_relations',
    {
        revision_id: text()
            .notNull()
            .references(() => revisions.id, { onDelete: 'cascade' }),
        field_path: text().notNull(),
        target_entry_id: text()
            .notNull()
            .references(() => entries.id, { onDelete: 'restrict' }),
        position: integer().notNull(),
        required: integer().notNull(),
    },
    (table) => [
        primaryKey({ columns: [table.revision_id, table.field_path, table.position] }),
        index('site_admin_relations_target').on(table.target_entry_id),
    ],
)

export const assetRefs = sqliteTable(
    'site_admin_asset_refs',
    {
        revision_id: text()
            .notNull()
            .references(() => revisions.id, { onDelete: 'cascade' }),
        field_path: text().notNull(),
        asset_id: text()
            .notNull()
            .references(() => assets.id, { onDelete: 'restrict' }),
        position: integer().notNull(),
    },
    (table) => [
        primaryKey({ columns: [table.revision_id, table.field_path, table.position] }),
        index('site_admin_asset_refs_asset').on(table.asset_id),
    ],
)

export const routes = sqliteTable(
    'site_admin_routes',
    {
        path: text().notNull(),
        locale: text().notNull().default(''),
        entry_id: text()
            .notNull()
            .references(() => entries.id, { onDelete: 'cascade' }),
        revision_id: text().references(() => revisions.id, { onDelete: 'cascade' }),
        kind: text().notNull(),
        target_path: text(),
        status: integer(),
        created_at: text().notNull(),
    },
    (table) => [
        primaryKey({ columns: [table.locale, table.path] }),
        index('site_admin_routes_entry').on(table.entry_id),
    ],
)

export const meta = sqliteTable('site_admin_meta', {
    key: text().primaryKey(),
    value: text().notNull(),
})

export const content_776f726b73 = sqliteTable('site_admin_content_works', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    title: text('field_title').notNull(),
    description: text('field_description'),
    category: text('field_category'),
    image: text('field_image', { mode: 'json' }),
    icon: text('field_icon'),
    href: text('field_href'),
    price: text('field_price'),
    style: text('field_style').notNull(),
    createdAt: text('field_createdAt'),
})
export const content_61727473 = sqliteTable('site_admin_content_arts', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    title: text('field_title').notNull(),
    description: text('field_description'),
    href: text('field_href'),
    images: text('field_images', { mode: 'json' }).notNull(),
    createdAt: text('field_createdAt'),
})
export const content_63617265657273 = sqliteTable('site_admin_content_careers', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    period: text('field_period').notNull(),
    position: text('field_position').notNull(),
    company: text('field_company').notNull(),
})
export const content_72616e6b73 = sqliteTable('site_admin_content_ranks', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    game: text('field_game').notNull(),
    season: text('field_season'),
    rank: text('field_rank').notNull(),
    image: text('field_image', { mode: 'json' }).notNull(),
    href: text('field_href'),
})
export const content_736b696c6c73 = sqliteTable('site_admin_content_skills', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    name: text('field_name').notNull(),
    icon: text('field_icon').notNull(),
    category: text('field_category'),
})
export const content_736f6369616c73 = sqliteTable('site_admin_content_socials', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    href: text('field_href').notNull(),
    icon: text('field_icon').notNull(),
    label: text('field_label').notNull(),
})
export const content_706f737473 = sqliteTable('site_admin_content_posts', {
    revisionId: text('revision_id')
        .primaryKey()
        .references(() => revisions.id, { onDelete: 'cascade' }),
    title: text('field_title').notNull(),
    // Retain retired excerpt storage and historical values; the model no longer uses it.
    excerpt: text('field_excerpt'),
    content: text('field_content').notNull(),
    publication: text('field_publication', { mode: 'json' }),
    tags: text('field_tags', { mode: 'json' }).notNull(),
    image: text('field_image', { mode: 'json' }),
    authorUserId: text('field_authorUserId'),
    createdAt: text('field_createdAt'),
})

export const users = sqliteTable('users', {
    id: text('id').primaryKey(),
    name: text('name').notNull(),
    email: text('email').notNull().unique(),
    emailVerified: integer('email_verified', { mode: 'boolean' }).default(false).notNull(),
    image: text('image'),
    createdAt: integer('created_at', { mode: 'timestamp_ms' })
        .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
        .notNull(),
    updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
        .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
        .$onUpdate(() => /* @__PURE__ */ new Date())
        .notNull(),
    role: text('role'),
    banned: integer('banned', { mode: 'boolean' }).default(false),
    banReason: text('ban_reason'),
    banExpires: integer('ban_expires', { mode: 'timestamp_ms' }),
})

export const sessions = sqliteTable(
    'sessions',
    {
        id: text('id').primaryKey(),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        token: text('token').notNull().unique(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
        ipAddress: text('ip_address'),
        userAgent: text('user_agent'),
        userId: text('user_id')
            .notNull()
            .references(() => users.id, { onDelete: 'cascade' }),
        impersonatedBy: text('impersonated_by'),
    },
    (table) => [index('sessions_userId_idx').on(table.userId)],
)

export const accounts = sqliteTable(
    'accounts',
    {
        id: text('id').primaryKey(),
        accountId: text('account_id').notNull(),
        providerId: text('provider_id').notNull(),
        userId: text('user_id')
            .notNull()
            .references(() => users.id, { onDelete: 'cascade' }),
        accessToken: text('access_token'),
        refreshToken: text('refresh_token'),
        idToken: text('id_token'),
        accessTokenExpiresAt: integer('access_token_expires_at', {
            mode: 'timestamp_ms',
        }),
        refreshTokenExpiresAt: integer('refresh_token_expires_at', {
            mode: 'timestamp_ms',
        }),
        scope: text('scope'),
        password: text('password'),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
        issuer: text('issuer'),
    },
    (table) => [index('accounts_userId_idx').on(table.userId)],
)

export const verifications = sqliteTable(
    'verifications',
    {
        id: text('id').primaryKey(),
        identifier: text('identifier').notNull(),
        value: text('value').notNull(),
        expiresAt: integer('expires_at', { mode: 'timestamp_ms' }).notNull(),
        createdAt: integer('created_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .notNull(),
        updatedAt: integer('updated_at', { mode: 'timestamp_ms' })
            .default(sql`(cast(unixepoch('subsecond') * 1000 as integer))`)
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [index('verifications_identifier_idx').on(table.identifier)],
)

export const passkeys = sqliteTable(
    'passkeys',
    {
        id: text('id').primaryKey(),
        name: text('name'),
        publicKey: text('public_key').notNull(),
        userId: text('user_id')
            .notNull()
            .references(() => users.id, { onDelete: 'cascade' }),
        credentialID: text('credential_id').notNull(),
        counter: integer('counter').notNull(),
        deviceType: text('device_type').notNull(),
        backedUp: integer('backed_up', { mode: 'boolean' }).notNull(),
        transports: text('transports'),
        createdAt: integer('created_at', { mode: 'timestamp_ms' }),
        aaguid: text('aaguid'),
    },
    (table) => [
        index('passkeys_userId_idx').on(table.userId),
        index('passkeys_credentialID_idx').on(table.credentialID),
    ],
)

export const jwks = sqliteTable('jwks', {
    id: text('id').primaryKey(),
    publicKey: text('public_key').notNull(),
    privateKey: text('private_key').notNull(),
    createdAt: integer('created_at', { mode: 'timestamp_ms' }).notNull(),
    expiresAt: integer('expires_at', { mode: 'timestamp_ms' }),
    alg: text('alg'),
    crv: text('crv'),
})

export const rateLimits = sqliteTable('rate_limits', {
    id: text('id').primaryKey(),
    key: text('key').notNull().unique(),
    count: integer('count').notNull(),
    lastRequest: integer('last_request').notNull(),
})

export const authRelations = defineRelationsPart(
    { users, sessions, accounts, verifications, passkeys, jwks, rateLimits },
    (r) => ({
        users: {
            sessions: r.many.sessions({
                from: r.users.id,
                to: r.sessions.userId,
            }),
            accounts: r.many.accounts({
                from: r.users.id,
                to: r.accounts.userId,
            }),
            passkeys: r.many.passkeys({
                from: r.users.id,
                to: r.passkeys.userId,
            }),
        },
        sessions: {
            user: r.one.users({
                from: r.sessions.userId,
                to: r.users.id,
            }),
        },
        accounts: {
            user: r.one.users({
                from: r.accounts.userId,
                to: r.users.id,
            }),
        },
        passkeys: {
            user: r.one.users({
                from: r.passkeys.userId,
                to: r.users.id,
            }),
        },
    }),
)
